-- Generated by Oracle SQL Developer Data Modeler 17.3.0.261.1541
--   at:        2018-12-16 19:19:13 GMT
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2

-- DROPS
DROP TABLE "MONITOR"."DATAFILES" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."TABLESPACES" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."USERS" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."SESSIONS" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."SGA" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."SGA_HIST" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."PGA" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."PGA_HIST" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."CPU" CASCADE CONSTRAINTS;
DROP TABLE "MONITOR"."CPU_HIST" CASCADE CONSTRAINTS;



-- "TABLESPACES
CREATE TABLE "MONITOR"."TABLESPACES" (
    "name"        VARCHAR2(100) NOT NULL,
    "filecount"   NUMBER NOT NULL,
    "size"        NUMBER NOT NULL,
    "free"        NUMBER NOT NULL,
    "used"        NUMBER NOT NULL,
    "maxextend"   NUMBER NOT NULL,
    "percfree"    NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT TABLESPACES_PK PRIMARY KEY ( "name" )
)
LOGGING;



-- "DATAFILES
CREATE TABLE "MONITOR"."DATAFILES" (
    "filename"         VARCHAR2(300) NOT NULL,
    "fileid"           NUMBER NOT NULL,
    "tablename"        VARCHAR2(100) NOT NULL,
    "bytes"            NUMBER NOT NULL,
    "blocks"           NUMBER NOT NULL,
    "status"           VARCHAR2(100) NOT NULL,
    "autoextensible"   VARCHAR2(100) NOT NULL,
    "maxbytes"         NUMBER NOT NULL,
    "maxblocks"        NUMBER NOT NULL,
    "onlinestatus"     VARCHAR2(100) NOT NULL,
    "timestamp"        TIMESTAMP NOT NULL,
    CONSTRAINT DATAFILES_PK PRIMARY KEY ( "filename" ),
    CONSTRAINT DATAFILES_TABLESPACES_FK FOREIGN KEY ( "tablename" )
        REFERENCES "MONITOR"."TABLESPACES" ( "name" )
)
LOGGING;



-- "USERS
CREATE TABLE "MONITOR"."USERS" (
    "username"            VARCHAR2(100) NOT NULL,
    "accStatus"           VARCHAR2(100) NOT NULL,
    "common"              VARCHAR2(100) NOT NULL,
    "expiryDate"          DATE,
    "defaultTablespace"   VARCHAR2(100) NOT NULL,
    "tempTablespace"      VARCHAR2(100) NOT NULL,
    "profile"             VARCHAR2(100) NOT NULL,
    "created"             DATE NOT NULL,
    "timestamp"           TIMESTAMP NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY ( "username" , "defaultTablespace" ),
    CONSTRAINT USERS_TABLESPACES_FK FOREIGN KEY ( "defaultTablespace" )
        REFERENCES "MONITOR"."TABLESPACES" ( "name" )
)
LOGGING;



-- "SESSIONS
CREATE TABLE "MONITOR"."SESSIONS" (
    "sid"         VARCHAR2(100) NOT NULL,
    "username"    VARCHAR2(100) NOT NULL,
    "status"      VARCHAR2(100) NOT NULL,
    "server"      VARCHAR2(100) NOT NULL,
    "schemaName"  VARCHAR2(100) NOT NULL,
    "osUser"      VARCHAR2(100) NOT NULL,
    "machine"     VARCHAR2(100) NOT NULL,
    "port"        NUMBER NOT NULL,
    "type"        VARCHAR2(100),
    "logonTime"   DATE NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT SESSIONS_PK PRIMARY KEY ( "sid" ),
    CONSTRAINT SESSIONS_USERS_FK FOREIGN KEY ( "username" )
        REFERENCES "MONITOR"."USERS" ( "username" )
)
LOGGING;



-- "SGA (faz sentido ter histórico p/ gráfico de barras)
CREATE TABLE "MONITOR"."SGA" (
    "name"        VARCHAR2(100) NOT NULL,
    "total"       NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT SGA_PK PRIMARY KEY ( "name" )
)
LOGGING;

-- HISTÓRICO "SGA
CREATE TABLE "MONITOR"."SGA_HIST" (
    "name"        VARCHAR2(100) NOT NULL,
    "total"       NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT SGA_HIST_PK PRIMARY KEY ( "name","timestamp" )
)
LOGGING;



-- "PGA (faz sentido ter histórico p/ gráfico de barras)
CREATE TABLE "MONITOR"."PGA" (
    "name"        VARCHAR2(100) NOT NULL,
    "usedPga"     NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
     CONSTRAINT PGA_PK PRIMARY KEY ( "name" )
)
LOGGING;

-- HISTÓRICO "PGA
CREATE TABLE "MONITOR"."PGA_HIST" (
    "name"        VARCHAR2(100) NOT NULL,
    "usedPga"     NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT PGA_HIST_PK PRIMARY KEY ( "name","timestamp" )
)
LOGGING;



-- "CPU (faz sentido ter histórico p/ gráfico de barras)
CREATE TABLE "MONITOR"."CPU" (
    "username"    VARCHAR2(100) NOT NULL,
    "cpuUsage"    NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT CPU_PK PRIMARY KEY ( "username" )
)
LOGGING;

-- HISTÓRICO "CPU
CREATE TABLE "MONITOR"."CPU_HIST" (
    "username"    VARCHAR2(100) NOT NULL,
    "cpuUsage"    NUMBER NOT NULL,
    "timestamp"   TIMESTAMP NOT NULL,
    CONSTRAINT CPU_HIST_PK PRIMARY KEY ( "username","timestamp" )
)
LOGGING;


-- CHECK
SELECT * FROM "MONITOR"."DATAFILES";
SELECT * FROM "MONITOR"."TABLESPACES";
SELECT * FROM "MONITOR"."USERS";
SELECT * FROM "MONITOR"."SESSIONS";
SELECT * FROM "MONITOR"."SGA";
SELECT * FROM "MONITOR"."SGA_HIST";
SELECT * FROM "MONITOR"."PGA";
SELECT * FROM "MONITOR"."PGA_HIST";
SELECT * FROM "MONITOR"."CPU";
SELECT * FROM "MONITOR"."CPU_HIST";