SELECT * FROM Jobs 
    WHERE Jobs.MIN_SALARY >= 10000;
    
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME, HIRE_DATE FROM employees
    WHERE HIRE_DATE >= to_date('01-01-2002','DD-MM-YYYY') AND HIRE_DATE <= to_date('31-12-2004','DD-MM-YYYY')
    ORDER BY HIRE_DATE;
    
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME, HIRE_DATE FROM employees
    INNER JOIN jobs ON employees.JOB_ID = jobs.JOB_ID
    WHERE JOB_TITLE LIKE 'Programmer' OR JOB_TITLE LIKE 'Sales Manager'
    ORDER BY HIRE_DATE;

SELECT * FROM employees
	WHERE HIRE_DATE >= to_date('01-01-2008','DD-MM-YYYY');

SELECT * FROM employees 
	WHERE EMPLOYEE_ID >= 140 AND EMPLOYEE_ID <= 170;

SELECT LAST_NAME, COMMISSION_PCT, HIRE_DATE FROM employees
	WHERE SALARY < 12000;

SELECT JOB_TITLE, MAX_SALARY - MIN_SALARY AS SALARYDIF FROM jobs 
	WHERE MAX_SALARY >= 10000 AND MAX_SALARY <= 20000;

SELECT FIRST_NAME, SALARY, SALARY / 1000 FROM employees; 

SELECT * FROM jobs 
	ORDER BY JOB_TITLE DESC;

SELECT * FROM employees 
	WHERE SUBSTR(FIRST_NAME,-1,1) = 's' AND SUBSTR(LAST_NAME,1,1) = 'J'; 

SELECT * FROM employees 
	WHERE EXTRACT(MONTH FROM HIRE_DATE) = '06';

SELECT * FROM employees 
    WHERE COMMISSION_PCT = NULL AND DEPARTMENT_ID = 30 AND SALARY > 5000 AND SALARY < 10000;
    
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME FROM employees 
	WHERE EXTRACT(YEAR FROM HIRE_DATE) = '2001';

SELECT NVL(SUBSTR(JOB_TITLE,1,INSTR(JOB_TITLE,' ')), JOB_TITLE) AS FIRST_WORD FROM jobs;

SELECT FIRST_NAME, LAST_NAME FROM employees 
	WHERE INSTR(SUBSTR(LAST_NAME,4),'b') > 0;

SELECT * FROM employees 
	WHERE EXTRACT(YEAR FROM HIRE_DATE) = EXTRACT(YEAR FROM SYSDATE);

SELECT ROUND(SYSDATE - TO_DATE('01-01-2001','DD-MM-YYYY'),0) AS TOTAL_DAYS FROM dual; 

SELECT to_char(hire_Date, 'mm') AS MONTH, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES
    WHERE to_char(hire_Date, 'yyyy') = to_char(sysdate, 'yyyy') 
    GROUP BY to_char(hire_Date, 'mm');

SELECT C.COUNTRY_NAME, COUNT(L.CITY) FROM COUNTRIES C
	INNER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    GROUP BY C.COUNTRY_NAME;

SELECT D.DEPARTMENT_NAME, AVG(E.SALARY) FROM departments D 
	INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE E.COMMISSION_PCT IS NOT NULL
    GROUP BY D.DEPARTMENT_NAME;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
	VALUES (500, 'Joana', 'Caldas', 'NKOCHHAR1', '991.791.891', to_date('01-01-1997','DD-MM-YYYY'), 'AD_PRES', 5000, null, 100, 90);

UPDATE EMPLOYEES
SET SALARY = CASE WHEN EMPLOYEES.SALARY <= 6000 THEN 8000
            END WHERE EMPLOYEES.EMPLOYEE_ID = 115;

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) FROM departments D 
	INNER JOIN employees E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_NAME;

SELECT j.JOB_TITLE, e.EMPLOYEE_ID, jh.END_DATE - jh.START_DATE AS DAYS FROM JOB_HISTORY jh
    INNER JOIN JOBS j ON jh.JOB_ID=j.JOB_ID
    INNER JOIN EMPLOYEES e ON jh.EMPLOYEE_ID=e.EMPLOYEE_ID
    WHERE jh.DEPARTMENT_ID=30;

SELECT J.JOB_TITLE, D.DEPARTMENT_NAME, E.LAST_NAME, E.HIRE_DATE FROM EMPLOYEES E
	JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
	JOIN JOBS J ON E.JOB_ID = J.JOB_ID
    WHERE HIRE_DATE >= TO_DATE('01-01-2000', 'DD-MM-YYYY') AND HIRE_DATE <= TO_DATE('31-12-2005', 'DD-MM-YYYY');

SELECT J.JOB_TITLE, AVG(E.SALARY) AS MEAN_SALARY FROM JOBS J 
	INNER JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
    GROUP BY JOB_TITLE; 

SELECT J.JOB_TITLE,(J.MAX_SALARY-E.SALARY) AS DIF FROM JOBS J 
	INNER JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID;

SELECT J.JOB_TITLE, E.EMPLOYEE_ID FROM JOBS J 
	INNER JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
    WHERE E.SALARY >= 15000;

SELECT CONCAT(E1.FIRST_NAME, E1.LAST_NAME) AS FULL_NAME FROM EMPLOYEES E1
    INNER JOIN EMPLOYEES E2 ON E1.MANAGER_ID=e2.EMPLOYEE_ID
    WHERE E1.HIRE_DATE<E2.HIRE_DATE;

SELECT CONCAT(E.FIRST_NAME, E.LAST_NAME) AS FULL_NAME, C.COUNTRY_NAME FROM EMPLOYEES E 
    INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
    INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID;

SELECT TO_CHAR(E.HIRE_DATE, 'mm') AS MONTH FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
    WHERE L.CITY = 'Seattle'
    GROUP BY TO_CHAR(E.HIRE_DATE, 'mm')
    HAVING COUNT (TO_CHAR(E.HIRE_DATE, 'mm')) > 5;

SELECT C.COUNTRY_NAME, L.CITY, COUNT(D.DEPARTMENT_ID) FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
    INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
    GROUP BY L.CITY, C.COUNTRY_NAME
    HAVING COUNT (EMPLOYEE_ID) > 5;

-- Não está bem
SELECT E1.FIRST_NAME FROM EMPLOYEES E1
    WHERE E1.MANAGER_ID=(SELECT E2.EMPLOYEE_ID FROM EMPLOYEES E2
                        WHERE E2.EMPLOYEE_ID=E1.EMPLOYEE_ID)
    GROUP BY E1.FIRST_NAME
    HAVING COUNT(E1.EMPLOYEE_ID) > 5;

SELECT CITY FROM LOCATIONS l
    INNER JOIN DEPARTMENTS d ON l.LOCATION_ID = d.LOCATION_ID 
    INNER JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
    WHERE EMPLOYEE_ID = 105;